name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  GITHUB_TOKEN: # change this
    required: true
    description: 'Please add in your gihub token'
runs:
  using: 'node12'
  main: 'dist/index.js'
